"""add_document_approval

Revision ID: 037bbca4c49a
Revises: 0a6956bf8478
Create Date: 2026-07-27 01:51:57.211877
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '037bbca4c49a'
down_revision: Union[str, None] = '0a6956bf8478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_document_approval',
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('step_order', sa.SmallInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['tab_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tab_document_approval')
    # ### end Alembic commands ###
