"""numbering_rule_update

Revision ID: 0a6956bf8478
Revises: 617bcc83a42a
Create Date: 2026-07-25 08:51:21.595587
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0a6956bf8478'
down_revision: Union[str, None] = '617bcc83a42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_numbering_rule', sa.Column('start_number', sa.BigInteger(), nullable=False))
    op.add_column('tab_numbering_rule', sa.Column('is_editable', sa.Boolean(), nullable=False))
    op.add_column('tab_numbering_rule', sa.Column('is_all_doc_types', sa.Boolean(), nullable=False))
    op.add_column('tab_numbering_rule', sa.Column('doc_type_ids', sa.JSON(), nullable=False))
    op.add_column('tab_numbering_rule', sa.Column('is_all_books', sa.Boolean(), nullable=False))
    op.add_column('tab_numbering_rule', sa.Column('is_no_book', sa.Boolean(), nullable=False))
    op.add_column('tab_numbering_rule', sa.Column('book_ids', sa.JSON(), nullable=False))
    op.alter_column('tab_numbering_rule', 'reset_cycle',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_constraint('tab_numbering_rule_ibfk_1', 'tab_numbering_rule', type_='foreignkey')
    op.drop_column('tab_numbering_rule', 'doc_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_numbering_rule', sa.Column('doc_type_id', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('tab_numbering_rule_ibfk_1', 'tab_numbering_rule', 'tab_doc_type', ['doc_type_id'], ['id'])
    op.alter_column('tab_numbering_rule', 'reset_cycle',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('tab_numbering_rule', 'book_ids')
    op.drop_column('tab_numbering_rule', 'is_no_book')
    op.drop_column('tab_numbering_rule', 'is_all_books')
    op.drop_column('tab_numbering_rule', 'doc_type_ids')
    op.drop_column('tab_numbering_rule', 'is_all_doc_types')
    op.drop_column('tab_numbering_rule', 'is_editable')
    op.drop_column('tab_numbering_rule', 'start_number')
    # ### end Alembic commands ###
