"""dms_init

Revision ID: 0dce7a9e09ff
Revises: 
Create Date: 2026-07-24 02:13:43.173763
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dce7a9e09ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_audit_log',
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_audit_log_entity'), 'tab_audit_log', ['entity'], unique=False)
    op.create_index(op.f('ix_tab_audit_log_entity_id'), 'tab_audit_log', ['entity_id'], unique=False)
    op.create_table('tab_company',
    sa.Column('code', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_code', sa.String(length=25), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('invoice_email', sa.String(length=255), nullable=False),
    sa.Column('parent', sa.BigInteger(), nullable=False),
    sa.Column('legal_representative_id', sa.BigInteger(), nullable=True),
    sa.Column('legal_rep_title', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tab_department',
    sa.Column('code', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('parent', sa.BigInteger(), nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tab_doc_type',
    sa.Column('org_unit_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('is_versioned', sa.Boolean(), nullable=False),
    sa.Column('needs_decision', sa.Boolean(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_email_log',
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_employee',
    sa.Column('code', sa.String(length=25), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tab_field_config',
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('org_unit_id', sa.BigInteger(), nullable=True),
    sa.Column('field_key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_file',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_file_link',
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('purchase_order_id', sa.BigInteger(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_file_link_doc_type'), 'tab_file_link', ['doc_type'], unique=False)
    op.create_index(op.f('ix_tab_file_link_entity'), 'tab_file_link', ['entity'], unique=False)
    op.create_index(op.f('ix_tab_file_link_entity_id'), 'tab_file_link', ['entity_id'], unique=False)
    op.create_index(op.f('ix_tab_file_link_file_id'), 'tab_file_link', ['file_id'], unique=False)
    op.create_table('tab_import_batch',
    sa.Column('module', sa.SmallInteger(), nullable=False),
    sa.Column('mode', sa.SmallInteger(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sheet_info', sa.Text(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_import_batch_module'), 'tab_import_batch', ['module'], unique=False)
    op.create_index(op.f('ix_tab_import_batch_status'), 'tab_import_batch', ['status'], unique=False)
    op.create_table('tab_import_change',
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('survey_id', sa.BigInteger(), nullable=False),
    sa.Column('was_new', sa.SmallInteger(), nullable=False),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_import_change_batch_id'), 'tab_import_change', ['batch_id'], unique=False)
    op.create_table('tab_import_log',
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('sheet', sa.String(length=40), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ref_key', sa.String(length=120), nullable=False),
    sa.Column('target_code', sa.String(length=50), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_import_log_batch_id'), 'tab_import_log', ['batch_id'], unique=False)
    op.create_index(op.f('ix_tab_import_log_level'), 'tab_import_log', ['level'], unique=False)
    op.create_table('tab_notification',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_notification_user_id'), 'tab_notification', ['user_id'], unique=False)
    op.create_table('tab_numbering_counter',
    sa.Column('scope_key', sa.String(length=200), nullable=False),
    sa.Column('current_no', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_key')
    )
    op.create_table('tab_partner',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_permission',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=False),
    sa.Column('can_write', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('can_approve', sa.Boolean(), nullable=False),
    sa.Column('can_cancel', sa.Boolean(), nullable=False),
    sa.Column('can_print', sa.Boolean(), nullable=False),
    sa.Column('can_export', sa.Boolean(), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_permission_entity'), 'tab_permission', ['entity'], unique=False)
    op.create_index(op.f('ix_tab_permission_role_id'), 'tab_permission', ['role_id'], unique=False)
    op.create_table('tab_product',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('invoice_name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('item_group', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=25), nullable=False),
    sa.Column('hh_code', sa.String(length=50), nullable=False),
    sa.Column('hh_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_tab_product_hh_code'), 'tab_product', ['hh_code'], unique=False)
    op.create_table('tab_push_subscription',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_push_subscription_user_id'), 'tab_push_subscription', ['user_id'], unique=False)
    op.create_table('tab_register_book',
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('org_unit_id', sa.BigInteger(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_report_snapshot',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_report_snapshot_key'), 'tab_report_snapshot', ['key'], unique=True)
    op.create_table('tab_role',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tab_secrecy_level',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tab_setting',
    sa.Column('skey', sa.String(length=64), nullable=False),
    sa.Column('svalue', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_setting_skey'), 'tab_setting', ['skey'], unique=True)
    op.create_table('tab_urgency_level',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('sla_hours', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tab_user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('google_sub', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_user_email'), 'tab_user', ['email'], unique=False)
    op.create_index(op.f('ix_tab_user_employee_id'), 'tab_user', ['employee_id'], unique=False)
    op.create_table('tab_user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_user_role_role_id'), 'tab_user_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_tab_user_role_user_id'), 'tab_user_role', ['user_id'], unique=False)
    op.create_table('tab_user_scope',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('dim', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('is_exclude', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_user_scope_entity'), 'tab_user_scope', ['entity'], unique=False)
    op.create_index(op.f('ix_tab_user_scope_role_id'), 'tab_user_scope', ['role_id'], unique=False)
    op.create_index(op.f('ix_tab_user_scope_user_id'), 'tab_user_scope', ['user_id'], unique=False)
    op.create_table('tab_document',
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=True),
    sa.Column('org_unit_id', sa.BigInteger(), nullable=False),
    sa.Column('doc_type_id', sa.BigInteger(), nullable=False),
    sa.Column('doc_no', sa.String(length=100), nullable=True),
    sa.Column('seq_no', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body_summary', sa.Text(), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('partner_id', sa.BigInteger(), nullable=True),
    sa.Column('signer_id', sa.BigInteger(), nullable=True),
    sa.Column('signer_title', sa.String(length=150), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('secrecy_id', sa.BigInteger(), nullable=True),
    sa.Column('urgency_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_version', sa.SmallInteger(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['tab_register_book.id'], ),
    sa.ForeignKeyConstraint(['doc_type_id'], ['tab_doc_type.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['tab_partner.id'], ),
    sa.ForeignKeyConstraint(['secrecy_id'], ['tab_secrecy_level.id'], ),
    sa.ForeignKeyConstraint(['urgency_id'], ['tab_urgency_level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_numbering_rule',
    sa.Column('org_unit_id', sa.BigInteger(), nullable=True),
    sa.Column('direction', sa.SmallInteger(), nullable=True),
    sa.Column('doc_type_id', sa.BigInteger(), nullable=True),
    sa.Column('template', sa.String(length=200), nullable=False),
    sa.Column('reset_cycle', sa.String(length=10), nullable=False),
    sa.Column('padding', sa.SmallInteger(), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['doc_type_id'], ['tab_doc_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_register_book_manager',
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['tab_register_book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_register_book_viewer',
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['tab_register_book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_document_file',
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('version_no', sa.SmallInteger(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('is_signed', sa.Boolean(), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['tab_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_document_link',
    sa.Column('from_document_id', sa.BigInteger(), nullable=False),
    sa.Column('to_document_id', sa.BigInteger(), nullable=True),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('link_type', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['from_document_id'], ['tab_document.id'], ),
    sa.ForeignKeyConstraint(['to_document_id'], ['tab_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_document_version',
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('version_no', sa.SmallInteger(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('superseded_by', sa.BigInteger(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['tab_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tab_document_version')
    op.drop_table('tab_document_link')
    op.drop_table('tab_document_file')
    op.drop_table('tab_register_book_viewer')
    op.drop_table('tab_register_book_manager')
    op.drop_table('tab_numbering_rule')
    op.drop_table('tab_document')
    op.drop_index(op.f('ix_tab_user_scope_user_id'), table_name='tab_user_scope')
    op.drop_index(op.f('ix_tab_user_scope_role_id'), table_name='tab_user_scope')
    op.drop_index(op.f('ix_tab_user_scope_entity'), table_name='tab_user_scope')
    op.drop_table('tab_user_scope')
    op.drop_index(op.f('ix_tab_user_role_user_id'), table_name='tab_user_role')
    op.drop_index(op.f('ix_tab_user_role_role_id'), table_name='tab_user_role')
    op.drop_table('tab_user_role')
    op.drop_index(op.f('ix_tab_user_employee_id'), table_name='tab_user')
    op.drop_index(op.f('ix_tab_user_email'), table_name='tab_user')
    op.drop_table('tab_user')
    op.drop_table('tab_urgency_level')
    op.drop_index(op.f('ix_tab_setting_skey'), table_name='tab_setting')
    op.drop_table('tab_setting')
    op.drop_table('tab_secrecy_level')
    op.drop_table('tab_role')
    op.drop_index(op.f('ix_tab_report_snapshot_key'), table_name='tab_report_snapshot')
    op.drop_table('tab_report_snapshot')
    op.drop_table('tab_register_book')
    op.drop_index(op.f('ix_tab_push_subscription_user_id'), table_name='tab_push_subscription')
    op.drop_table('tab_push_subscription')
    op.drop_index(op.f('ix_tab_product_hh_code'), table_name='tab_product')
    op.drop_table('tab_product')
    op.drop_index(op.f('ix_tab_permission_role_id'), table_name='tab_permission')
    op.drop_index(op.f('ix_tab_permission_entity'), table_name='tab_permission')
    op.drop_table('tab_permission')
    op.drop_table('tab_partner')
    op.drop_table('tab_numbering_counter')
    op.drop_index(op.f('ix_tab_notification_user_id'), table_name='tab_notification')
    op.drop_table('tab_notification')
    op.drop_index(op.f('ix_tab_import_log_level'), table_name='tab_import_log')
    op.drop_index(op.f('ix_tab_import_log_batch_id'), table_name='tab_import_log')
    op.drop_table('tab_import_log')
    op.drop_index(op.f('ix_tab_import_change_batch_id'), table_name='tab_import_change')
    op.drop_table('tab_import_change')
    op.drop_index(op.f('ix_tab_import_batch_status'), table_name='tab_import_batch')
    op.drop_index(op.f('ix_tab_import_batch_module'), table_name='tab_import_batch')
    op.drop_table('tab_import_batch')
    op.drop_index(op.f('ix_tab_file_link_file_id'), table_name='tab_file_link')
    op.drop_index(op.f('ix_tab_file_link_entity_id'), table_name='tab_file_link')
    op.drop_index(op.f('ix_tab_file_link_entity'), table_name='tab_file_link')
    op.drop_index(op.f('ix_tab_file_link_doc_type'), table_name='tab_file_link')
    op.drop_table('tab_file_link')
    op.drop_table('tab_file')
    op.drop_table('tab_field_config')
    op.drop_table('tab_employee')
    op.drop_table('tab_email_log')
    op.drop_table('tab_doc_type')
    op.drop_table('tab_department')
    op.drop_table('tab_company')
    op.drop_index(op.f('ix_tab_audit_log_entity_id'), table_name='tab_audit_log')
    op.drop_index(op.f('ix_tab_audit_log_entity'), table_name='tab_audit_log')
    op.drop_table('tab_audit_log')
    # ### end Alembic commands ###
