"""subject company

Revision ID: 163b52e80d50
Revises: dcc091d2527f
Create Date: 2026-07-28 10:06:25.807211
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163b52e80d50'
down_revision: Union[str, None] = 'dcc091d2527f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_subject_company',
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['tab_subject.id'], ),
    sa.PrimaryKeyConstraint('subject_id', 'company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tab_subject_company')
    # ### end Alembic commands ###
