"""Add title_code to JobTitle

Revision ID: 21a421a517c8
Revises: 9aa5350009e8
Create Date: 2026-07-27 05:26:37.519810
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a421a517c8'
down_revision: Union[str, None] = '9aa5350009e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_job_title', sa.Column('title_code', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_tab_job_title_title_code'), 'tab_job_title', ['title_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tab_job_title_title_code'), table_name='tab_job_title')
    op.drop_column('tab_job_title', 'title_code')
    # ### end Alembic commands ###
