"""urgency_level_add_desc_float_sla

Revision ID: 617bcc83a42a
Revises: df61cf0e1935
Create Date: 2026-07-25 08:40:15.209369
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '617bcc83a42a'
down_revision: Union[str, None] = 'df61cf0e1935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_urgency_level', sa.Column('description', sa.Text(), nullable=False))
    op.alter_column('tab_urgency_level', 'sla_hours',
               existing_type=mysql.SMALLINT(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tab_urgency_level', 'sla_hours',
               existing_type=sa.Float(),
               type_=mysql.SMALLINT(),
               existing_nullable=False)
    op.drop_column('tab_urgency_level', 'description')
    # ### end Alembic commands ###
