"""update_job_position_model

Revision ID: 7a614f90aac1
Revises: aabb5b41488d
Create Date: 2026-07-24 03:54:25.810356
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7a614f90aac1'
down_revision: Union[str, None] = 'aabb5b41488d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_job_title', sa.Column('title_name', sa.String(length=255), nullable=False))
    op.add_column('tab_job_title', sa.Column('description', sa.String(length=500), nullable=True))
    op.drop_index('name', table_name='tab_job_title')
    op.create_unique_constraint(None, 'tab_job_title', ['title_name'])
    op.drop_column('tab_job_title', 'name')
    op.add_column('tab_position_group', sa.Column('group_name', sa.String(length=255), nullable=False))
    op.add_column('tab_position_group', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('tab_position_group', sa.Column('sort_order', sa.BigInteger(), nullable=False))
    op.drop_index('name', table_name='tab_position_group')
    op.create_unique_constraint(None, 'tab_position_group', ['group_name'])
    op.drop_column('tab_position_group', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_position_group', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'tab_position_group', type_='unique')
    op.create_index('name', 'tab_position_group', ['name'], unique=True)
    op.drop_column('tab_position_group', 'sort_order')
    op.drop_column('tab_position_group', 'description')
    op.drop_column('tab_position_group', 'group_name')
    op.add_column('tab_job_title', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'tab_job_title', type_='unique')
    op.create_index('name', 'tab_job_title', ['name'], unique=True)
    op.drop_column('tab_job_title', 'description')
    op.drop_column('tab_job_title', 'title_name')
    # ### end Alembic commands ###
