"""Add subject departments and job titles

Revision ID: 9aa5350009e8
Revises: 037bbca4c49a
Create Date: 2026-07-27 03:11:15.767831
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aa5350009e8'
down_revision: Union[str, None] = '037bbca4c49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_subject_department',
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['tab_subject.id'], ),
    sa.PrimaryKeyConstraint('subject_id', 'department_id')
    )
    op.create_table('tab_subject_job_title',
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('job_title_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['tab_subject.id'], ),
    sa.PrimaryKeyConstraint('subject_id', 'job_title_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tab_subject_job_title')
    op.drop_table('tab_subject_department')
    # ### end Alembic commands ###
