"""Add OrgUnit, JobPosition, Subject

Revision ID: 9b4f707be9bd
Revises: cac8b8d0b3ac
Create Date: 2026-07-24 03:30:37.434093
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9b4f707be9bd'
down_revision: Union[str, None] = 'cac8b8d0b3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_job_title',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.BigInteger(), nullable=False),
    sa.Column('is_inactive', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tab_org_unit',
    sa.Column('parent_id', sa.BigInteger(), nullable=False),
    sa.Column('unit_code', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('unit_name', sa.String(length=255), nullable=False),
    sa.Column('org_level', sa.String(length=50), nullable=False),
    sa.Column('accounting_type', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('functions_duties', sa.String(length=500), nullable=True),
    sa.Column('business_reg_no', sa.String(length=50), nullable=True),
    sa.Column('business_reg_date', sa.Date(), nullable=True),
    sa.Column('business_reg_place', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_inactive', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_org_unit_unit_code'), 'tab_org_unit', ['unit_code'], unique=True)
    op.create_table('tab_org_unit_business_area',
    sa.Column('org_unit_id', sa.BigInteger(), nullable=False),
    sa.Column('business_area', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('org_unit_id', 'business_area')
    )
    op.create_table('tab_position_group',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_inactive', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tab_subject',
    sa.Column('is_user', sa.Boolean(), nullable=False),
    sa.Column('is_employee', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('mobile_phone', sa.String(length=20), nullable=True),
    sa.Column('personal_email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('job_position_id', sa.BigInteger(), nullable=True),
    sa.Column('account_phone', sa.String(length=20), nullable=True),
    sa.Column('account_email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=False),
    sa.Column('user_status', sa.String(length=20), nullable=False),
    sa.Column('employee_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code')
    )
    op.create_index(op.f('ix_tab_subject_account_email'), 'tab_subject', ['account_email'], unique=True)
    op.create_index(op.f('ix_tab_subject_account_phone'), 'tab_subject', ['account_phone'], unique=True)
    op.create_table('tab_subject_org_unit',
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('org_unit_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('subject_id', 'org_unit_id')
    )
    op.create_table('tab_subject_role',
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_subject_role_role_id'), 'tab_subject_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_tab_subject_role_subject_id'), 'tab_subject_role', ['subject_id'], unique=False)
    op.create_table('tab_subject_scope',
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('dim', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('is_exclude', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_subject_scope_entity'), 'tab_subject_scope', ['entity'], unique=False)
    op.create_index(op.f('ix_tab_subject_scope_role_id'), 'tab_subject_scope', ['role_id'], unique=False)
    op.create_index(op.f('ix_tab_subject_scope_subject_id'), 'tab_subject_scope', ['subject_id'], unique=False)
    op.create_table('tab_job_position',
    sa.Column('position_code', sa.String(length=20), nullable=False),
    sa.Column('position_name', sa.String(length=255), nullable=False),
    sa.Column('position_group_id', sa.BigInteger(), nullable=True),
    sa.Column('job_title_id', sa.BigInteger(), nullable=True),
    sa.Column('is_inactive', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['job_title_id'], ['tab_job_title.id'], ),
    sa.ForeignKeyConstraint(['position_group_id'], ['tab_position_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_job_position_position_code'), 'tab_job_position', ['position_code'], unique=True)
    op.create_table('tab_job_position_org_unit',
    sa.Column('job_position_id', sa.BigInteger(), nullable=False),
    sa.Column('org_unit_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['job_position_id'], ['tab_job_position.id'], ),
    sa.PrimaryKeyConstraint('job_position_id', 'org_unit_id')
    )
    op.drop_index('ix_tab_user_scope_entity', table_name='tab_user_scope')
    op.drop_index('ix_tab_user_scope_role_id', table_name='tab_user_scope')
    op.drop_index('ix_tab_user_scope_user_id', table_name='tab_user_scope')
    op.drop_table('tab_user_scope')
    op.drop_index('code', table_name='tab_employee')
    op.drop_table('tab_employee')
    op.drop_index('code', table_name='tab_department')
    op.drop_table('tab_department')
    op.drop_index('ix_tab_user_email', table_name='tab_user')
    op.drop_index('ix_tab_user_employee_id', table_name='tab_user')
    op.drop_table('tab_user')
    op.drop_index('ix_tab_user_role_role_id', table_name='tab_user_role')
    op.drop_index('ix_tab_user_role_user_id', table_name='tab_user_role')
    op.drop_table('tab_user_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_user_role',
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_by', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_tab_user_role_user_id', 'tab_user_role', ['user_id'], unique=False)
    op.create_index('ix_tab_user_role_role_id', 'tab_user_role', ['role_id'], unique=False)
    op.create_table('tab_user',
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('google_sub', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('employee_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('avatar', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_by', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_tab_user_employee_id', 'tab_user', ['employee_id'], unique=False)
    op.create_index('ix_tab_user_email', 'tab_user', ['email'], unique=False)
    op.create_table('tab_department',
    sa.Column('code', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('company_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('parent', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('manager_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_by', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('code', 'tab_department', ['code'], unique=True)
    op.create_table('tab_employee',
    sa.Column('code', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('company_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('department_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('position', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('role_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_by', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('code', 'tab_employee', ['code'], unique=True)
    op.create_table('tab_user_scope',
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('entity', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('dim', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('value', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('is_exclude', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_by', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_tab_user_scope_user_id', 'tab_user_scope', ['user_id'], unique=False)
    op.create_index('ix_tab_user_scope_role_id', 'tab_user_scope', ['role_id'], unique=False)
    op.create_index('ix_tab_user_scope_entity', 'tab_user_scope', ['entity'], unique=False)
    op.drop_table('tab_job_position_org_unit')
    op.drop_index(op.f('ix_tab_job_position_position_code'), table_name='tab_job_position')
    op.drop_table('tab_job_position')
    op.drop_index(op.f('ix_tab_subject_scope_subject_id'), table_name='tab_subject_scope')
    op.drop_index(op.f('ix_tab_subject_scope_role_id'), table_name='tab_subject_scope')
    op.drop_index(op.f('ix_tab_subject_scope_entity'), table_name='tab_subject_scope')
    op.drop_table('tab_subject_scope')
    op.drop_index(op.f('ix_tab_subject_role_subject_id'), table_name='tab_subject_role')
    op.drop_index(op.f('ix_tab_subject_role_role_id'), table_name='tab_subject_role')
    op.drop_table('tab_subject_role')
    op.drop_table('tab_subject_org_unit')
    op.drop_index(op.f('ix_tab_subject_account_phone'), table_name='tab_subject')
    op.drop_index(op.f('ix_tab_subject_account_email'), table_name='tab_subject')
    op.drop_table('tab_subject')
    op.drop_table('tab_position_group')
    op.drop_table('tab_org_unit_business_area')
    op.drop_index(op.f('ix_tab_org_unit_unit_code'), table_name='tab_org_unit')
    op.drop_table('tab_org_unit')
    op.drop_table('tab_job_title')
    # ### end Alembic commands ###
