"""update_job_position_model_2

Revision ID: a468a6b84e30
Revises: 7a614f90aac1
Create Date: 2026-07-24 03:55:37.198697
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a468a6b84e30'
down_revision: Union[str, None] = '7a614f90aac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_job_position', sa.Column('group_id', sa.BigInteger(), nullable=True))
    op.add_column('tab_job_position', sa.Column('title_id', sa.BigInteger(), nullable=True))
    op.add_column('tab_job_position', sa.Column('report_to_position_id', sa.BigInteger(), nullable=True))
    op.add_column('tab_job_position', sa.Column('description', sa.String(length=500), nullable=True))
    op.drop_constraint('tab_job_position_ibfk_1', 'tab_job_position', type_='foreignkey')
    op.drop_constraint('tab_job_position_ibfk_2', 'tab_job_position', type_='foreignkey')
    op.create_foreign_key(None, 'tab_job_position', 'tab_job_title', ['title_id'], ['id'])
    op.create_foreign_key(None, 'tab_job_position', 'tab_position_group', ['group_id'], ['id'])
    op.create_foreign_key(None, 'tab_job_position', 'tab_job_position', ['report_to_position_id'], ['id'])
    op.drop_column('tab_job_position', 'job_title_id')
    op.drop_column('tab_job_position', 'position_group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_job_position', sa.Column('position_group_id', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('tab_job_position', sa.Column('job_title_id', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tab_job_position', type_='foreignkey')
    op.drop_constraint(None, 'tab_job_position', type_='foreignkey')
    op.drop_constraint(None, 'tab_job_position', type_='foreignkey')
    op.create_foreign_key('tab_job_position_ibfk_2', 'tab_job_position', 'tab_position_group', ['position_group_id'], ['id'])
    op.create_foreign_key('tab_job_position_ibfk_1', 'tab_job_position', 'tab_job_title', ['job_title_id'], ['id'])
    op.drop_column('tab_job_position', 'description')
    op.drop_column('tab_job_position', 'report_to_position_id')
    op.drop_column('tab_job_position', 'title_id')
    op.drop_column('tab_job_position', 'group_id')
    # ### end Alembic commands ###
