"""rename_subject_fields

Revision ID: aabb5b41488d
Revises: 9b4f707be9bd
Create Date: 2026-07-24 03:48:31.752929
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aabb5b41488d'
down_revision: Union[str, None] = '9b4f707be9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tab_org_unit_business_area', 'tab_org_unit', ['org_unit_id'], ['id'])
    op.add_column('tab_subject', sa.Column('subject_name', sa.String(length=100), nullable=False))
    op.add_column('tab_subject', sa.Column('contact_phone', sa.String(length=20), nullable=True))
    op.add_column('tab_subject', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('tab_subject', sa.Column('subject_code', sa.String(length=50), nullable=True))
    op.add_column('tab_subject', sa.Column('direct_manager_id', sa.BigInteger(), nullable=True))
    op.add_column('tab_subject', sa.Column('join_date', sa.Date(), nullable=True))
    op.add_column('tab_subject', sa.Column('probation_date', sa.Date(), nullable=True))
    op.add_column('tab_subject', sa.Column('official_date', sa.Date(), nullable=True))
    op.add_column('tab_subject', sa.Column('resign_date', sa.Date(), nullable=True))
    op.drop_index('employee_code', table_name='tab_subject')
    op.create_unique_constraint(None, 'tab_subject', ['subject_code'])
    op.drop_column('tab_subject', 'mobile_phone')
    op.drop_column('tab_subject', 'employee_code')
    op.drop_column('tab_subject', 'full_name')
    op.drop_column('tab_subject', 'personal_email')
    op.create_foreign_key(None, 'tab_subject_org_unit', 'tab_subject', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tab_subject_org_unit', type_='foreignkey')
    op.add_column('tab_subject', sa.Column('personal_email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('tab_subject', sa.Column('full_name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('tab_subject', sa.Column('employee_code', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('tab_subject', sa.Column('mobile_phone', mysql.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'tab_subject', type_='unique')
    op.create_index('employee_code', 'tab_subject', ['employee_code'], unique=True)
    op.drop_column('tab_subject', 'resign_date')
    op.drop_column('tab_subject', 'official_date')
    op.drop_column('tab_subject', 'probation_date')
    op.drop_column('tab_subject', 'join_date')
    op.drop_column('tab_subject', 'direct_manager_id')
    op.drop_column('tab_subject', 'subject_code')
    op.drop_column('tab_subject', 'contact_email')
    op.drop_column('tab_subject', 'contact_phone')
    op.drop_column('tab_subject', 'subject_name')
    op.drop_constraint(None, 'tab_org_unit_business_area', type_='foreignkey')
    # ### end Alembic commands ###
