"""Add document security tables

Revision ID: b01e4ef224bd
Revises: 21a421a517c8
Create Date: 2026-07-27 06:28:40.052693
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b01e4ef224bd'
down_revision: Union[str, None] = '21a421a517c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_approval_flow_config',
    sa.Column('doc_type_id', sa.BigInteger(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['doc_type_id'], ['tab_doc_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_doc_security_policy',
    sa.Column('doc_type_id', sa.BigInteger(), nullable=True),
    sa.Column('secrecy_id', sa.BigInteger(), nullable=True),
    sa.Column('requires_2fa', sa.Boolean(), nullable=False),
    sa.Column('allowed_roles', sa.JSON(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['doc_type_id'], ['tab_doc_type.id'], ),
    sa.ForeignKeyConstraint(['secrecy_id'], ['tab_secrecy_level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_doc_access_log',
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['tab_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tab_doc_access_request',
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('requester_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['tab_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tab_document', sa.Column('is_hot_locked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_document', 'is_hot_locked')
    op.drop_table('tab_doc_access_request')
    op.drop_table('tab_doc_access_log')
    op.drop_table('tab_doc_security_policy')
    op.drop_table('tab_approval_flow_config')
    # ### end Alembic commands ###
