"""update_job_position_schema

Revision ID: b0a85da73ecb
Revises: b01e4ef224bd
Create Date: 2026-07-28 01:44:59.995180
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b0a85da73ecb'
down_revision: Union[str, None] = 'b01e4ef224bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_job_position_company',
    sa.Column('job_position_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['job_position_id'], ['tab_job_position.id'], ),
    sa.PrimaryKeyConstraint('job_position_id', 'company_id')
    )
    op.drop_table('tab_job_position_org_unit')
    op.add_column('tab_job_position', sa.Column('department_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('tab_job_position_ibfk_2', 'tab_job_position', type_='foreignkey')
    op.drop_constraint('tab_job_position_ibfk_3', 'tab_job_position', type_='foreignkey')
    op.create_foreign_key(None, 'tab_job_position', 'tab_department', ['department_id'], ['id'])
    op.drop_column('tab_job_position', 'report_to_position_id')
    op.drop_column('tab_job_position', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_job_position', sa.Column('group_id', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('tab_job_position', sa.Column('report_to_position_id', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tab_job_position', type_='foreignkey')
    op.create_foreign_key('tab_job_position_ibfk_3', 'tab_job_position', 'tab_job_position', ['report_to_position_id'], ['id'])
    op.create_foreign_key('tab_job_position_ibfk_2', 'tab_job_position', 'tab_position_group', ['group_id'], ['id'])
    op.drop_column('tab_job_position', 'department_id')
    op.create_table('tab_job_position_org_unit',
    sa.Column('job_position_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('org_unit_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_position_id'], ['tab_job_position.id'], name='tab_job_position_org_unit_ibfk_1'),
    sa.PrimaryKeyConstraint('job_position_id', 'org_unit_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('tab_job_position_company')
    # ### end Alembic commands ###
