"""update_company_fields

Revision ID: cac8b8d0b3ac
Revises: 0dce7a9e09ff
Create Date: 2026-07-24 02:47:55.485031
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac8b8d0b3ac'
down_revision: Union[str, None] = '0dce7a9e09ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_company', sa.Column('short_name', sa.String(length=255), nullable=False))
    op.add_column('tab_company', sa.Column('logo', sa.Text(), nullable=False))
    op.add_column('tab_company', sa.Column('business_type', sa.String(length=100), nullable=False))
    op.add_column('tab_company', sa.Column('foundation_date', sa.String(length=20), nullable=False))
    op.add_column('tab_company', sa.Column('business_registration_code', sa.String(length=50), nullable=False))
    op.add_column('tab_company', sa.Column('issue_date', sa.String(length=20), nullable=False))
    op.add_column('tab_company', sa.Column('issue_place', sa.String(length=255), nullable=False))
    op.add_column('tab_company', sa.Column('legal_rep_name', sa.String(length=100), nullable=False))
    op.add_column('tab_company', sa.Column('province', sa.String(length=100), nullable=False))
    op.add_column('tab_company', sa.Column('district', sa.String(length=100), nullable=False))
    op.add_column('tab_company', sa.Column('ward', sa.String(length=100), nullable=False))
    op.add_column('tab_company', sa.Column('phone', sa.String(length=50), nullable=False))
    op.add_column('tab_company', sa.Column('fax', sa.String(length=50), nullable=False))
    op.add_column('tab_company', sa.Column('website', sa.String(length=255), nullable=False))
    op.add_column('tab_company', sa.Column('is_group_model', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_company', 'is_group_model')
    op.drop_column('tab_company', 'website')
    op.drop_column('tab_company', 'fax')
    op.drop_column('tab_company', 'phone')
    op.drop_column('tab_company', 'ward')
    op.drop_column('tab_company', 'district')
    op.drop_column('tab_company', 'province')
    op.drop_column('tab_company', 'legal_rep_name')
    op.drop_column('tab_company', 'issue_place')
    op.drop_column('tab_company', 'issue_date')
    op.drop_column('tab_company', 'business_registration_code')
    op.drop_column('tab_company', 'foundation_date')
    op.drop_column('tab_company', 'business_type')
    op.drop_column('tab_company', 'logo')
    op.drop_column('tab_company', 'short_name')
    # ### end Alembic commands ###
