"""add vpn_access to tab_subject

Revision ID: dcc091d2527f
Revises: b0a85da73ecb
Create Date: 2026-07-28 09:18:00.731610
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc091d2527f'
down_revision: Union[str, None] = 'b0a85da73ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tab_subject', sa.Column('vpn_access', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab_subject', 'vpn_access')
    # ### end Alembic commands ###
